Current runner version: '2.321.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
Download action repository 'actions/setup-python@v4' (SHA:65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236)
Download action repository 'codecov/codecov-action@v3' (SHA:ab904c41d6ece82784817410c45d8b8c02684457)
Complete job name: test
20s
4s
Determining the checkout info
Checking out the ref
/usr/bin/git log -1 --format='%H'
'1ad28d6898185b6410c1a0b8081293385c7ba9cc'
0s
Run actions/setup-python@v4
Installed versions
30s
1s
Run pytest --cov=. --cov-report=xml
/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/config/__init__.py:328: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: helpconfig, Hook: pytest_cmdline_parse
ConftestImportFailure: ModuleNotFoundError: No module named 'main' (from /home/runner/work/ERP/ERP/tests/conftest.py)
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config = pluginmanager.hook.pytest_cmdline_parse(
ImportError while loading conftest '/home/runner/work/ERP/ERP/tests/conftest.py'.
tests/conftest.py:9: in <module>
    from main import app
E   ModuleNotFoundError: No module named 'main'
Error: Process completed with exit code 4.